name: CI API
on:
  push:
    branches: [ main ]
    paths: [ 'BackEnd/**' , '.github/workflows/**']
  pull_request:
    branches: [ main ]
    paths: [ 'BackEnd/**' , '.github/workflows/**']
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - working-directory: ./BackEnd
        name: Restore
        run: dotnet restore
      - working-directory: ./BackEnd
        name: Build
        run: dotnet build --no-restore
      - working-directory: ./BackEnd
        name: Test
        run: dotnet test --no-build --verbosity normal
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_DEPLOY_HOOK }}
          method: 'POST'