name: CI Frontend
on:
  push:
    branches: [ main , develop]
    paths: [ 'ReactFrontEnd/**', '.github/workflows/**' ]
  pull_request:
    branches: [ main , develop]
    paths: [ 'ReactFrontEnd/**', '.github/workflows/**' ]
permissions:
  contents: read
  pull-requests: write 
  deployments: write 
  statuses: write 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - working-directory: ./ReactFrontEnd
        run: npm ci
      - working-directory: ./ReactFrontEnd
        name: Run Tests
        run: npm test
      - working-directory: ./ReactFrontEnd
        name: Build
        run: npm run build
  quality-security-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ReactFrontEnd
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Format Check
        run: npm run format -- --check
      - name: Lint
        run: npm run lint
      - name: Test with Coverage
        run: npm test -- --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false  # Add this to disable comments
          vercel-args: '--prod'
          working-directory: . # use . as the root directory because we only select the ReactFrontEnd folder for deployment to Vercel from the Github repo
  